-- 코드를 입력하세요
SELECT PRODUCT_CODE
    , SUM(SALES) AS SALES
FROM
(SELECT  PRODUCT_CODE
      , PRICE * SALES_AMOUNT AS SALES
FROM
(SELECT P.PRODUCT_ID
    , P.PRODUCT_CODE
    , P.PRICE
    , OS.OFFLINE_SALE_ID
    , OS.SALES_AMOUNT
    , OS.SALES_DATE
FROM PRODUCT P INNER JOIN OFFLINE_SALE OS
    ON P.PRODUCT_ID = OS.PRODUCT_ID))
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE