-- 코드를 입력하세요
SELECT NAME
        , DATETIME
FROM
    (SELECT AI.NAME
          , AI.DATETIME
          , RANK() OVER (ORDER BY AI.DATETIME ASC) AS RANK
    FROM ANIMAL_INS AI LEFT JOIN ANIMAL_OUTS AO
        ON AI.ANIMAL_ID = AO.ANIMAL_ID
    WHERE AO.ANIMAL_ID IS NULL)
WHERE RANK <= 3;
